### PR TITLE
SCF Files Moved in 2016 Survey

### PR DESCRIPTION
**Pull request by dqydj**
Looks like the files were moved. I updated the paths for only 2016.

### CODE REVIEW

**Comment by ajdamico** [comment]
thank you!  could you update them all?

**Comment by dqydj** [comment]
Oh - hadn't even checked the others @ajdamico , ha. They're all there with names changed it seems (just tried this morning). This one should grab them

**Comment by ajdamico** [comment]
thanks very much

**Comment by ajdamico** [comment]
http://asdfree.com/survey-of-consumer-finances-scf.html   passes all tests..thank you again

**Comment by dqydj** [comment]
Thank you for the great package!

**Comment by ajdamico** [comment]
hi @dqydj i think you're one year ahead in https://dqydj.com/income-percentile-by-age-calculator/
the march 2017 cps-asec gets fielded in february-april 2017 but contains 2016 annualized dollars..  https://www.census.gov/data/tables/2017/demo/income-poverty/p60-259.html

**Comment by dqydj** [comment]
Yeah, that bit has been tough to point out on those posts - I try to shoot the gap between "this is the newest data/2017 release" and "an income earned in full year (Jan- Dec) 2016". What would you think to clarify?

**Pull request merged**
